apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web-client
    app.kubernetes.io/instance: picture-upload-demo
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: picture-upload
    app.kubernetes.io/managed-by: kubectl
  name: web-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - command:
            - npm
            - run
            - prod
          image: 629054125090.dkr.ecr.us-east-1.amazonaws.com/web-client:latest
          imagePullPolicy: Always
          name: web-client
          ports:
            - containerPort: 3000
          env:
            - name: FILTER_HOST
              value: photo-filter
            - name: STORAGE_HOST
              value: photo-storage
            - name: DEBUG
              value: '*'
