apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: photo-storage
    app.kubernetes.io/instance: picture-upload-demo
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: picture-upload
    app.kubernetes.io/managed-by: kubectl
  name: photo-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-storage
  template:
    metadata:
      labels:
        app: photo-storage
    spec:
      containers:
        - image: 629054125090.dkr.ecr.us-east-1.amazonaws.com/photo-storage:latest
          imagePullPolicy: Always
          name: photo-storage
          ports:
            - containerPort: 3001
          command:
            - npm
            - run
            - prod
